channels:
  - conda-forge

dependencies:
  - astropy
  - dask
  - fitsverify
  - hstcal
  - h5py
  - ipython
  - jupyter
  - numpy
  - pip
  - pytables
  - python
  - pytest
  - pytest-xdist
  - scipy
  - scikit-image
  - sphinx
  - pip:
      - acstools
      - asdf
      - calcos
      - ccdproc
      - ci-watson
      - costools
      - crds
      - drizzlepac
      - ginga
      - jwst
      - nictools
      - pysynphot
      - reftools
      - stcal
      - stdatamodels
      - stistools
      - stsynphot
      - stregion
      - synphot
      - wfc3tools
      - wfpc2tools
