name: release

on:
  push:
    paths:
      - "**/*.yml"

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: build environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: mtkennerly/dunamai-action@v1.1.0
        id: version
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-current
          key: conda-${{ runner.os }}-${{ hashFiles('spacetelescope-env-latest.yml') }}-${{ steps.version.outputs.version }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-env-current
          environment-file: spacetelescope-env-latest.yml
          use-only-tar-bz2: true
      - run: conda env export > spacetelescope-env-${{ steps.version.outputs.version }}.yml
      - run: sed -i "s/spacetelescope-env-current/spacetelescope-env-${{ steps.version.outputs.version }}/g" spacetelescope-env-${{ steps.version.outputs.version }}.yml
      - run: cat spacetelescope-env-${{ steps.version.outputs.version }}.yml
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: spacetelescope-env-${{ steps.version.outputs.version }}.yml
          path: spacetelescope-env-${{ steps.version.outputs.version }}.yml
  test:
    name: test environment
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: acstools
            repository: https://github.com/spacetelescope/acstools.git
          - package: calcos
            repository: https://github.com/spacetelescope/calcos.git
          - package: ccdproc
            repository: https://github.com/astropy/ccdproc.git
          - package: costools
            repository: https://github.com/spacetelescope/costools.git
          - package: crds
            repository: https://github.com/spacetelescope/crds.git
          - package: drizzlepac
            repository: https://github.com/spacetelescope/drizzlepac.git
          #- package: fitsverify
          #  repository:
          - package: hstcal
            repository: https://github.com/spacetelescope/hstcal.git
          #- package: nictools
          #  repository: https://github.com/spacetelescope/nictools.git
          - package: pysynphot
            repository: https://github.com/spacetelescope/pysynphot.git
          - package: reftools
            repository: https://github.com/spacetelescope/reftools.git
          - package: stistools
            repository: https://github.com/spacetelescope/stistools.git
          - package: stsynphot
            repository: https://github.com/spacetelescope/stsynphot.git
          - package: synphot
            repository: https://github.com/spacetelescope/synphot.git
          #- package: wfc3tools
          #  repository: https://github.com/spacetelescope/wfc3tools.git
          - package: wfpc2tools
            repository: https://github.com/spacetelescope/wfpc2tools.git
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: spacetelescope-env-distribution
      - uses: actions/checkout@v2.4.2
        with:
          repository: ${{ matrix.repository }}
          path: ${{ matrix.package }}
      - uses: mtkennerly/dunamai-action@v1.1.0
        id: version
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-current
          key: conda-${{ runner.os }}-${{ hashFiles('spacetelescope-env-latest.yml') }}-${{ steps.version.outputs.version }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-env-current
          environment-file: spacetelescope-env-latest.yml
          use-only-tar-bz2: true
      - run: pip install pytest-xdist ci-watson pytest-astropy-header
      - run: |
          cd ${{ matrix.package }}
          pytest -n auto .
  export:
    name: export environment
    needs: [ test ]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2.21.1
        with:
          name: spacetelescope-env-${{ steps.version.outputs.version }}.yml
          path: spacetelescope-env-${{ steps.version.outputs.version }}.yml
      - uses: svenstaro/upload-release-action@2.3.0
        with:
          file: spacetelescope-env-${{ steps.version.outputs.version }}.yml
