name: release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash -l {0}

env:
  LATEST_ENV_NAME: spacetelescope-env-latest
  RELEASE_ENV_NAME: spacetelescope-env-${{ github.event.release.tag_name }}

jobs:
  build:
    name: build environment
    runs-on: ubuntu-latest
    env:
      LATEST_ENV_FILENAME: releases/${{ env.LATEST_ENV_NAME }}.yml
      RELEASE_ENV_FILENAME: releases/${{ env.RELEASE_ENV_NAME }}.yml
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/test
          key:
            conda-${{ github.event.release.tag_name }}-${{ runner.os }}-${{ hashFiles('${{ env.LATEST_ENV_FILENAME }}') }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-env-${{ github.event.release.tag_name }}
          environment-file: ${{ env.LATEST_ENV_FILENAME }}
          use-only-tar-bz2: true
      - run: conda env export > ${{ env.RELEASE_ENV_FILENAME }}
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          file_pattern: ${{ env.RELEASE_ENV_FILENAME }}
          commit_message: release ${{ github.event.release.tag_name }}
      - uses: svenstaro/upload-release-action@2.3.0
        with:
          file: ${{ env.RELEASE_ENV_FILENAME }}


