name: release

on:
  push:
    paths:
      - "**/*.yml"

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: build environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-latest-env
          key: conda-${{ runner.os }}-${{ hashFiles('spacetelescope-env-latest.yml') }}-${{ env.GITHUB_SHA }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-latest-env
          environment-file: spacetelescope-env-latest.yml
          use-only-tar-bz2: true
  test:
    name: test environment
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - acstools
          - calcos
          - ccdproc
          - costools
          - crds
          - drizzlepac
#          - fitsverify
          - hstcal
#          - nictools
          - pysynphot
          - reftools
          - stistools
          - stsynphot
          - synphot
#          - wfc3tools
          - wfpc2tools
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-latest
          key: conda-${{ runner.os }}-${{ hashFiles('spacetelescope-env-latest.yml') }}-${{ env.GITHUB_SHA }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-latest-env
          environment-file: spacetelescope-env-latest.yml
          use-only-tar-bz2: true
      - run: pip install pytest-xdist
      - run: pytest -n auto --pyargs ${{ matrix.package }}
  export:
    name: export environment
    needs: [ test ]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-latest
          key: conda-${{ runner.os }}-${{ hashFiles('spacetelescope-env-latest.yml') }}-${{ env.GITHUB_SHA }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-env-latest
          environment-file: spacetelescope-env-latest.yml
          use-only-tar-bz2: true
      - run: conda env export > spacetelescope-env-${{ github.event.release.tag_name }}.yml
      - run: sed -i "s/spacetelescope-env-latest/spacetelescope-env-${{ github.event.release.tag_name }}/g" spacetelescope-env-${{ github.event.release.tag_name }}.yml
      - run: cat spacetelescope-env-${{ github.event.release.tag_name }}.yml
      - uses: svenstaro/upload-release-action@2.3.0
        with:
          file: spacetelescope-env-${{ github.event.release.tag_name }}.yml
